---
title: "Tabulating ldsc genetic correlation results" 
format: html
embed-resources: true
---

```{r}
library(magrittr)
```

```{r}
# read ldsc log files and extract stuff
ldsc_dir <- here::here("analysis", "data", "ldsc_genetic_correlations")
log_files <- list.files(ldsc_dir, pattern = ".log", full.names = TRUE)
df_list <- list()
for (lfile in log_files){
    print(lfile)
    n_lines <- R.utils::countLines(lfile)
    n_to_skip <- n_lines - 5
    ldf <- readr::read_table(lfile, skip = n_to_skip, n_max = 1, col_names = TRUE, col_types = "ccdddddddddd")
    df_list[[lfile]] <- ldf
}
df_logs <- df_list %>%
    dplyr::bind_rows() %>%
    dplyr::mutate(trait1 = p1 %>% basename() %>% stringr::str_remove(pattern = ".sumstats.gz"))

```

```{r}
# read downloaded tsv file
tsv_dir <- here::here("analysis", "data", "mrcieu")
tsv_files <- list.files(tsv_dir, pattern = ".tsv", full.names = TRUE)
df_list <- list()
for (file in tsv_files){
    print(file)
    df <- readr::read_tsv(file, col_names = FALSE, col_types = "cciccccciccicicccciiid")
    df_list[[file]] <- df
}
df_tsv <- df_list %>%
    dplyr::bind_rows() 
```


```{r}
# join dfs
df_tsv %>%
    dplyr::left_join(df_logs, by = c("X1" = "trait1")) %>%
    dplyr::filter(!is.na(gcov_int)) %>%
    dplyr::relocate(c(X2, rg, se, z, p, X12, X10)) %>%
    gt::gt()
```


## Session Info

```{r, session_info}
sessioninfo::session_info()
# git commit info
gr <- git2r::repository(here::here()) %>%
    git2r::commits()
gr[[1]] 
```
